services:
  - type: web
    name: fredium
    runtime: node
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://your-domain.onrender.com # Update with your domain
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
